services:
  app:
    build: 
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "8080:8080"
    command: [tail, -f, /dev/null]